#!/usr/bin/env python3
"""Minimal OpenAI-compatible chat-completions stub: answers every request with a canned reply
(streaming SSE when asked, JSON otherwise) and a usage block, so Goose can complete a real turn
and persist metadata_json.usage / usage_ledger rows without spending model calls."""
import json, sys, time
from http.server import BaseHTTPRequestHandler, HTTPServer

REPLY = "pong — generated by the cv test stub, no model involved."
calls = 0

class H(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        sys.stderr.write("stub: " + (fmt % args) + "\n")
    def do_GET(self):
        body = json.dumps({"object": "list", "data": [{"id": "stub-model", "object": "model"}]}).encode()
        self.send_response(200); self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body))); self.end_headers(); self.wfile.write(body)
    def do_POST(self):
        global calls
        n = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(n) if n else b"{}"
        try: req = json.loads(raw or b"{}")
        except Exception: req = {}
        calls += 1
        model = req.get("model", "stub-model")
        usage = {"prompt_tokens": 321 + calls, "completion_tokens": 17, "total_tokens": 338 + calls,
                 "prompt_tokens_details": {"cached_tokens": 100}}
        cid = f"chatcmpl-stub{calls}"
        if req.get("stream"):
            self.send_response(200); self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache"); self.end_headers()
            def chunk(delta, finish=None, extra=None):
                c = {"id": cid, "object": "chat.completion.chunk", "created": int(time.time()), "model": model,
                     "choices": [{"index": 0, "delta": delta, "finish_reason": finish}]}
                if extra: c.update(extra)
                self.wfile.write(f"data: {json.dumps(c)}\n\n".encode()); self.wfile.flush()
            chunk({"role": "assistant", "content": ""})
            for word in REPLY.split(" "):
                chunk({"content": word + " "})
            chunk({}, finish="stop")
            # OpenAI sends usage in a trailing chunk with empty choices when stream_options asks for it.
            c = {"id": cid, "object": "chat.completion.chunk", "created": int(time.time()), "model": model,
                 "choices": [], "usage": usage}
            self.wfile.write(f"data: {json.dumps(c)}\n\n".encode())
            self.wfile.write(b"data: [DONE]\n\n"); self.wfile.flush()
        else:
            body = json.dumps({"id": cid, "object": "chat.completion", "created": int(time.time()), "model": model,
                               "choices": [{"index": 0, "message": {"role": "assistant", "content": REPLY},
                                            "finish_reason": "stop"}], "usage": usage}).encode()
            self.send_response(200); self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body))); self.end_headers(); self.wfile.write(body)

if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 18080
    HTTPServer(("127.0.0.1", port), H).serve_forever()
